### ISSUE TITLE
Got the error from execution from installation.md

### ISSUE THREAD

**Issue by daiki-kimura** [IBM/AMR-CSLogic#4]
Got this error:

```
$ export FLASK_APP=./amr_verbnet_semantics/web_app/__init__.py; python -m flask run --host=0.0.0.0 --port=5000
 * Serving Flask app './amr_verbnet_semantics/web_app/__init__.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/flask/__main__.py", line 3, in <module>
    main()
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/flask/cli.py", line 995, in main
    cli.main(args=sys.argv[1:])
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/flask/cli.py", line 850, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/flask/cli.py", line 325, in __init__
    self._load_unlocked()
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/flask/cli.py", line 351, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/flask/cli.py", line 407, in load_app
    app = locate_app(self, import_name, name)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/flask/cli.py", line 260, in locate_app
    __import__(module_name)
  File "/home/daiki/code/loa-oss/third_party/amr-cslogic/amr_verbnet_semantics/web_app/__init__.py", line 22, in <module>
    importlib.import_module(user_module_name + '.' + submodule_name + '.' + module)
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/daiki/code/loa-oss/third_party/amr-cslogic/amr_verbnet_semantics/web_app/routes.py", line 14, in <module>
    from amr_verbnet_semantics.core.amr_verbnet_enhance import \
  File "/home/daiki/code/loa-oss/third_party/amr-cslogic/amr_verbnet_semantics/core/amr_verbnet_enhance.py", line 18, in <module>
    from amr_verbnet_semantics.core.spacy_nlp_parse import full_parsing
  File "/home/daiki/code/loa-oss/third_party/amr-cslogic/amr_verbnet_semantics/core/spacy_nlp_parse.py", line 5, in <module>
    import neuralcoref
  File "/home/daiki/anaconda3/envs/amr-verbnet-v5/lib/python3.7/site-packages/neuralcoref/__init__.py", line 3, in <module>
    from .neuralcoref import NeuralCoref
  File "cymem.pxd", line 1, in init neuralcoref.neuralcoref
ValueError: cymem.cymem.Pool has the wrong size, try recompiling. Expected 64, got 48
```

I have tried to change to spacy version which is mentioned here
https://github.com/huggingface/neuralcoref/issues/102
I got different error about cuda on `thinc`. 
(i guess it works with spacy 2.0.12 during under CognitiveHorizon https://github.com/CognitiveHorizons/AMR-CSLogic/blob/master/requirements.txt#L9)

**Comment by daiki-kimura** [comment]
Fixed by https://github.com/IBM/AMR-CSLogic/pull/3

**Comment by daiki-kimura** [comment]
Merged the fix
